RESULT_DIR=/review/result
NAMING_BLUEPRINT_PATH=/review/naming
MPFS_BLUEPRINT_PATH=/review/mpfs
SCRIPT_IDENTITY=/review/identity
GENESIS_DIR=/review/genesis
RETIREMENT_ROWS_WRAPPER=/tmp/singular-root-rival-shell-env-clean-gZNHzx/stub.sh
set +e
TMPDIR="${RESULT_DIR}/tmp" \
RIVAL_VARIANT='own-policy' \
NAMING_BLUEPRINT="${NAMING_BLUEPRINT_PATH}" \
MPFS_BLUEPRINT="${MPFS_BLUEPRINT_PATH}" \
NAMING_SCRIPT_IDENTITY="${SCRIPT_IDENTITY}" \
E2E_GENESIS_DIR="${GENESIS_DIR}" \
env -u RETIREMENT_CONTROL -u RECOVERY_CONTROL \
  "${RETIREMENT_ROWS_WRAPPER}"
set +e
TMPDIR="${RESULT_DIR}/tmp" \
RIVAL_VARIANT='copied-policy' \
NAMING_BLUEPRINT="${NAMING_BLUEPRINT_PATH}" \
MPFS_BLUEPRINT="${MPFS_BLUEPRINT_PATH}" \
NAMING_SCRIPT_IDENTITY="${SCRIPT_IDENTITY}" \
E2E_GENESIS_DIR="${GENESIS_DIR}" \
env -u RETIREMENT_CONTROL -u RECOVERY_CONTROL \
  "${RETIREMENT_ROWS_WRAPPER}"
set +e
TMPDIR="${RESULT_DIR}/tmp" \
RIVAL_VARIANT='forged-anchor' \
NAMING_BLUEPRINT="${NAMING_BLUEPRINT_PATH}" \
MPFS_BLUEPRINT="${MPFS_BLUEPRINT_PATH}" \
NAMING_SCRIPT_IDENTITY="${SCRIPT_IDENTITY}" \
E2E_GENESIS_DIR="${GENESIS_DIR}" \
env -u RETIREMENT_CONTROL -u RECOVERY_CONTROL \
  "${RETIREMENT_ROWS_WRAPPER}"
