{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE NumericUnderscores #-}

{- |
Module      : Singular.Registry.ContractSuite
Description : #326 — one backend contract, every adapter
License     : Apache-2.0

The read interface's contract, written once and run against every
adapter: the deterministic in-memory chain, a node reached by socket and
magic, and the index that follows a node. Each case is a requirement a
backend meets or refuses by name; an adapter that cannot exercise a case
says so in its harness, with the reason, and the suite reports that
case for that adapter as not supported — never as passed, and never
decided by catching a failure.

Every run names its evidence class: @test-adapter@ for a chain held in
memory, @devnet@ for a development node. No class names a public chain.

Every value a case compares against is read from the adapter at run
time — the point of a view, the outputs a fresh view answers — and the
chain change a consistency case makes is observed through another
route than the view under test, so a case cannot pass by reading what
it wrote.
-}
module Singular.Registry.ContractSuite
    ( -- * Harness
      AdapterHarness (..)
    , Chain (..)
    , EvidenceClass (..)
    , renderEvidence
    , IndexRefusal (..)

      -- * Cases
    , Case (..)
    , CaseKind (..)
    , caseKind
    , caseText

      -- * Suite
    , contractSuite
    , unsupportedControl
    ) where

import Control.Exception
    ( ErrorCall (..)
    , SomeException
    , displayException
    , throwIO
    , try
    )
import Control.Monad (unless)
import Data.Aeson (encode, object, (.=))
import Data.ByteString qualified as BS
import Data.ByteString.Lazy qualified as BSL
import Data.Char (isHexDigit, toLower)
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Text qualified as T
import Data.Time.Clock.POSIX (getPOSIXTime)
import Data.Word (Word32)
import System.Environment (lookupEnv)
import System.Exit (ExitCode (..))
import System.Process (readProcessWithExitCode)
import System.Timeout (timeout)
import Test.Hspec

import Cardano.Ledger.Address (Addr)
import Cardano.Ledger.Api.Tx.Out (TxOut)
import Cardano.Ledger.Hashes (ScriptHash)
import Cardano.Ledger.TxIn (TxIn)

import Singular.Registry.Ledger (ConwayEra)
import Singular.Registry.Node.IndexerView (IndexerViewFailure (..))
import Singular.Registry.Provider
    ( ChainPoint (..)
    , Provider (..)
    , SlotNo (..)
    , View (..)
    , ViewFailure (..)
    )
import Singular.Registry.Services qualified as Services

-- | Where a run's evidence comes from. There is no public-chain class.
data EvidenceClass
    = -- | A chain held in memory by the test.
      TestAdapter
    | -- | A development node, generated by the suite or started outside it.
      DevNet
    deriving stock (Eq, Show, Enum, Bounded)

renderEvidence :: EvidenceClass -> String
renderEvidence = \case
    TestAdapter -> "test-adapter"
    DevNet -> "devnet"

-- | What a case establishes.
data CaseKind = Success | Refusal | Consistency
    deriving stock (Eq, Show)

-- | The contract, case by case.
data Case
    = ViewNamesPoint
    | ReadsAnswer
    | OnePoint
    | ChangeUnseen
    | OutOfScope
    | ConnectionLost
    | AtOrigin
    | IndexLag
    | IndexFork
    | IndexRestoring
    | IndexDisconnected
    deriving stock (Eq, Ord, Show, Enum, Bounded)

caseKind :: Case -> CaseKind
caseKind = \case
    ViewNamesPoint -> Success
    ReadsAnswer -> Success
    OnePoint -> Consistency
    ChangeUnseen -> Consistency
    _ -> Refusal

-- | The requirement a case holds an adapter to.
caseText :: Case -> String
caseText = \case
    ViewNamesPoint ->
        "a view names the network, era, slot and block hash it was acquired at"
    ReadsAnswer ->
        "a view answers its reads: outputs at an address, script \
        \registration, time to slot"
    OnePoint ->
        "every read inside one view is answered at the view's chain point \
        \(slot and block hash) while the chain moves on"
    ChangeUnseen ->
        "a chain change between two reads is not observed inside the view; \
        \a fresh view sees it"
    OutOfScope -> "a view used after its scope fails as ViewOutOfScope"
    ConnectionLost ->
        "a connection lost inside a view fails its next read and the next \
        \acquisition as ViewConnectionLost"
    AtOrigin -> "acquiring at the chain origin fails as AcquiredAtOrigin"
    IndexLag -> "an index behind the node's point refuses the view as lag"
    IndexFork ->
        "an index holding another block at the node's slot refuses the view \
        \as fork"
    IndexRestoring -> "an index still restoring refuses the view as restoring"
    IndexDisconnected ->
        "an index whose upstream is disconnected refuses the view as \
        \disconnected"

-- | The index states a harness can put its adapter in.
data IndexRefusal = Lag | Fork | Restoring | Disconnected
    deriving stock (Eq, Show)

{- | One chain an adapter serves, fresh for one case, with the controls
that move it.
-}
data Chain = Chain
    { chProvider :: Provider IO
    -- ^ The adapter under test
    , chNetwork :: Word32
    -- ^ The network magic the chain runs, as the harness opened it
    , chWatched :: Addr
    -- ^ An address whose outputs 'chChange' alters
    , chUnregistered :: ScriptHash
    -- ^ A script credential with no registered reward account
    , chChange :: IO ()
    {- ^ Alter the outputs at 'chWatched' and return once the change is
    on chain, observed through another route than 'chProvider'
    -}
    , chLoseConnection :: IO ()
    -- ^ Drop the adapter's connection to its chain
    , chAtOrigin :: forall a. (Provider IO -> IO a) -> IO a
    -- ^ The same adapter over a chain still at its origin
    , chProvoke :: IndexRefusal -> IO ()
    -- ^ Put the adapter's index in a state it must refuse
    }

-- | An adapter, its evidence class, and the cases it cannot exercise.
data AdapterHarness = AdapterHarness
    { ahAdapter :: String
    -- ^ The adapter's name in the suite's output
    , ahEvidence :: EvidenceClass
    , ahNotSupported :: Map Case String
    -- ^ Cases this adapter cannot exercise, each with the reason
    , ahChain :: forall a. (Chain -> IO a) -> IO a
    -- ^ A fresh chain for one case
    }

{- | The control of a case a harness lists as not supported: the suite
never runs it, and a harness that forgot to list the case fails loudly
when the case runs it. An action, not a bottom value: chains are built
with strict fields.
-}
unsupportedControl :: String -> IO a
unsupportedControl what =
    throwIO . ErrorCall $
        "contract suite: " <> what <> " is not supported by this harness"

-- | The whole contract over one adapter.
contractSuite :: AdapterHarness -> Spec
contractSuite h =
    describe
        ( ahAdapter h
            <> " adapter [evidence: "
            <> renderEvidence (ahEvidence h)
            <> "]"
        )
        $ mapM_ one [minBound .. maxBound]
  where
    one c =
        it (show (caseKind c) <> ": " <> caseText c) $
            case Map.lookup c (ahNotSupported h) of
                Just reason -> do
                    record h c "not-supported" (Just reason)
                    pendingWith
                        ("not supported by the " <> ahAdapter h <> " adapter: " <> reason)
                Nothing -> do
                    outcome <-
                        try $
                            timeout caseBound (ahChain h (run c))
                                >>= maybe
                                    (expectationFailure "the case did not end within five minutes")
                                    pure
                    case outcome of
                        Right () -> record h c "passed" Nothing
                        Left (e :: SomeException) -> do
                            record h c "failed" (Just (displayException e))
                            throwIO e

{- | Append one case's result on one adapter to the results file named by
@CONTRACT_RESULTS@, one JSON object per line, when the variable is set:
the adapter, its evidence class, the case, its kind and requirement, the
outcome and its reason, and the code revision the run checked out with
whether its tree was clean. The published evidence page is computed from
these lines. A revision or tree state that cannot be read fails the case
and writes nothing: it is never recorded as a value.
-}
record :: AdapterHarness -> Case -> String -> Maybe String -> IO ()
record h c outcome reason =
    lookupEnv "CONTRACT_RESULTS" >>= \case
        Nothing -> pure ()
        Just path -> do
            base <- git ["rev-parse", "HEAD"]
            unless (length base == 40 && all isHexDigit base) $
                unreadable ("git rev-parse HEAD printed " <> show base)
            status <- git ["status", "--porcelain"]
            BSL.appendFile path . (<> "\n") . encode . object $
                [ "base" .= base
                , "dirty" .= not (null status)
                , "adapter" .= ahAdapter h
                , "evidence" .= renderEvidence (ahEvidence h)
                , "case" .= show c
                , "kind" .= map toLower (show (caseKind c))
                , "requirement" .= caseText c
                , "outcome" .= outcome
                ]
                    <> maybe [] (\r -> ["reason" .= r]) reason
  where
    git args = do
        (code, out, err) <- readProcessWithExitCode "git" args ""
        case code of
            ExitSuccess -> pure (filter (/= '\n') out)
            ExitFailure n ->
                unreadable
                    ( unwords ("git" : args)
                        <> " failed with exit "
                        <> show n
                        <> ": "
                        <> err
                    )
    unreadable why =
        throwIO . ErrorCall $
            "contract results: the run's revision or tree state cannot be read, \
            \so no result is written: "
                <> why

run :: Case -> Chain -> Expectation
run c ch = case c of
    ViewNamesPoint -> do
        point <- withView (chProvider ch) (pure . viewPoint)
        cpNetwork point `shouldBe` chNetwork ch
        T.null (cpEra point) `shouldBe` False
        BS.length (cpBlockHash point) `shouldBe` 32
    ReadsAnswer -> do
        chChange ch
        ms <- nowMs
        (outputs, registered, floorSlot, ceilSlot) <-
            withView (chProvider ch) $ \v -> do
                outputs <- viewUTxOsAt v (chWatched ch)
                registered <- viewScriptRegistered v (chUnregistered ch)
                (outputs,registered,,)
                    <$> Services.floorSlot v ms
                    <*> Services.ceilingSlot v ms
        outputs `shouldSatisfy` (not . null)
        registered `shouldBe` False
        floorSlot `shouldSatisfy` (<= ceilSlot)
    OnePoint -> do
        ms <- nowMs
        (early, late, point) <- aroundChange ch (observe ch ms)
        late `shouldBe` early
        fresh <- withView (chProvider ch) (pure . viewPoint)
        cpSlot fresh `shouldSatisfy` (> cpSlot point)
        cpBlockHash fresh `shouldNotBe` cpBlockHash point
    ChangeUnseen -> do
        (early, late, _) <-
            aroundChange ch $ \v -> viewUTxOsAt v (chWatched ch)
        late `shouldBe` early
        fresh <- withView (chProvider ch) (`viewUTxOsAt` chWatched ch)
        fresh `shouldNotBe` early
    OutOfScope -> do
        escaped <- withView (chProvider ch) pure
        r <- try (viewUTxOsAt escaped (chWatched ch))
        r `shouldBe` Left ViewOutOfScope
        s <- try (viewScriptRegistered escaped (chUnregistered ch))
        s `shouldBe` Left ViewOutOfScope
    ConnectionLost -> do
        inside <- withView (chProvider ch) $ \v -> do
            chLoseConnection ch
            try (viewScriptRegistered v (chUnregistered ch))
        inside `shouldBe` Left ViewConnectionLost
        next <- try (withView (chProvider ch) (pure . viewPoint))
        next `shouldBe` Left ViewConnectionLost
    AtOrigin -> chAtOrigin ch $ \origin -> do
        r <- try (withView origin (pure . viewPoint))
        r `shouldBe` Left AcquiredAtOrigin
    IndexLag -> refusedAs Lag $ \case IndexerLag{} -> True; _ -> False
    IndexFork -> refusedAs Fork $ \case IndexerFork{} -> True; _ -> False
    IndexRestoring ->
        refusedAs Restoring $ \case IndexerRestoring{} -> True; _ -> False
    IndexDisconnected ->
        refusedAs Disconnected $ \case IndexerDisconnected{} -> True; _ -> False
  where
    refusedAs state expected = do
        chProvoke ch state
        r <- try (withView (chProvider ch) (`viewUTxOsAt` chWatched ch))
        case r of
            Left failure
                | expected failure -> pure ()
                | otherwise -> expectationFailure ("refused as " <> show failure)
            Right answer -> expectationFailure ("answered: " <> show answer)

{- | Read through one view before and after a chain change made while the
view is held, with the view's point.
-}
aroundChange :: Chain -> (View IO -> IO r) -> IO (r, r, ChainPoint)
aroundChange ch readAll = withView (chProvider ch) $ \v -> do
    early <- readAll v
    chChange ch
    late <- readAll v
    pure (early, late, viewPoint v)

-- | Everything a view reads, the point included.
data Observed = Observed
    { obPoint :: ChainPoint
    , obOutputs :: [(TxIn, TxOut ConwayEra)]
    , obRegistered :: Bool
    , obSlot :: SlotNo
    , obParams :: String
    }
    deriving stock (Eq, Show)

observe :: Chain -> Integer -> View IO -> IO Observed
observe ch ms v =
    Observed (viewPoint v)
        <$> viewUTxOsAt v (chWatched ch)
        <*> viewScriptRegistered v (chUnregistered ch)
        <*> Services.floorSlot v ms
        <*> pure (show (viewProtocolParams v))

-- | The wall clock in POSIX milliseconds, inside every chain's horizon.
nowMs :: IO Integer
nowMs = floor . (* 1_000) <$> getPOSIXTime

{- | How long one case may take, generating its node included: a case
that waits for an answer that cannot come fails rather than hanging.
-}
caseBound :: Int
caseBound = 300_000_000
