import {initial,view,step} from './core.mjs';
// Illustrative defaults only: key 42, application destination 50, address datum A=100/B=200.
export const witnesses=(overrides={})=>({applicationMint:false,applicationSpend:false,nativeSpend:false,representativeMint:false,...overrides});
export function nextId(s){const n=Math.max(0,...s.used)+1;if(!Number.isSafeInteger(n))throw Error('invalid-nat/nextId');return n;}
export function makeInsert(s,{key=42,datum=100,id=nextId(s),scope=[view(s,key).entry.incarnation],assetScope=view(s,key).representative.assetScope,accepted=true,conforms=true}={}){
 const output={representative:{...view(s,key).representative,assetScope},quantity:1,destination:50,datum,value:20};
 const proposal={registry:s.config.registry,key,applicationPolicy:s.config.applicationPolicy,initial:output,scope};
 const asset={policy:s.config.applicationPolicy,name:{insert:{proposal}}};
 return {createInsert:{request:{id,operation:'insert',proposal,token:asset,held:null,destination:s.config.requestAddress,authenticatedOrigin:true},approval:{asset,accepted,conforms},witness:witnesses({applicationMint:true})}};
}
export function makeEvolution(s,source,datum,accepted=true){const old=s.applications.find(u=>u.id===source);if(!old)throw Error('application-unavailable');const successor={...old,id:nextId(s),output:{...old.output,datum}};return {evolve:{source,successor,evidence:{source,successor,accepted,conforms:true},witness:witnesses({applicationSpend:true})}};}
export function makeRelease(s,source,operation='update',accepted=true){const u=s.applications.find(u=>u.id===source);if(!u)throw Error('application-unavailable');const p=makeInsert(s,{key:u.key}).createInsert.request.proposal;const request={id:nextId(s),operation,proposal:p,token:null,held:u.output.representative,destination:s.config.requestAddress,authenticatedOrigin:true};return {release:{source,request,evidence:{source,request,accepted,conforms:true},witness:witnesses({applicationSpend:true})}};}
export function makeWithdrawal(s,id,destination=60,value=20){const refund={destination,value},asset={policy:s.config.applicationPolicy,name:{withdraw:{registry:s.config.registry,request:id,refund}}};return {mint:{mintWithdraw:{approval:{asset,accepted:true,conforms:true},witness:witnesses({applicationMint:true})}},withdraw:{withdraw:{request:id,asset,refund,witness:witnesses({nativeSpend:true})}}};}
export function makeFold(s,ids){let next=nextId(s);const items=ids.map(id=>{const r=s.requests.find(r=>r.id===id);return {request:id,outputId:r?.operation==='insert'?next++:0,output:r?.operation==='insert'?r.proposal.initial:null};});const mint=ids.flatMap(id=>{const r=s.requests.find(r=>r.id===id);return r?[{asset:r.operation==='insert'?r.proposal.initial.representative:r.held,quantity:r.operation==='insert'?1:-1}]:[];});return {fold:{items,mint,actionNet:[],witness:witnesses({nativeSpend:true,representativeMint:true})}};}
export const after=(s,a)=>{const r=step(s,a);if(!r.accepted)throw Error(r.reason);return r.value.state;};
