import {writeFileSync} from 'node:fs';
import {initial,step,resolve,inspect} from './core.mjs';
import {makeInsert,makeFold,makeRelease,makeEvolution,makeWithdrawal,after} from './actions.mjs';
const stories=[];
function story(id,title,goal,build){const st={id,title,goal,seed:initial(),steps:[],forks:[]};let s=st.seed;const add=(say,action)=>{const rec=inspect(s,action);st.steps.push({say,action,expect:rec.result});if(rec.result.accepted)s=rec.result.value.state;return s;};build(add,()=>s,st);stories.push(st);}
const register=(add,get)=>{add('Queue the approved Insert; no NFT exists yet.',makeInsert(get()));add('Fold the request; the application holds one representative NFT and resolves to address A.',makeFold(get(),[get().requests[0].id]));};
story('register','Register a name','Make name 42 resolve to address A (100).',(add,get)=>register(add,get));
story('compete','Two requests, one name','Fold one Insert and withdraw the competing request with separate approval.',(add,get,st)=>{add('Queue the first approved Insert.',makeInsert(get()));add('Queue a competing Insert for address B.',makeInsert(get(),{datum:200}));const both=get();const bad=makeFold(both,[1,2]);st.forks.push({at:2,title:'Try folding both: the entire batch is refused',steps:[{say:'The second item sees the first item’s active key. Neither item commits.',action:bad,expect:step(both,bad)}]});add('Fold the first request; the second remains pending.',makeFold(get(),[1]));const wd=makeWithdrawal(get(),2);add('Mint a separate approval bound to the competing request and exact refund.',wd.mint);add('Withdraw the competing Insert; address A remains live.',wd.withdraw);});
story('cancel','Cancel a pending Insert','Remove the request before it creates a representative NFT.',(add,get)=>{add('Queue an approved Insert.',makeInsert(get()));const wd=makeWithdrawal(get(),1);add('Approve this request’s exact withdrawal and refund.',wd.mint);add('Withdraw the pending Insert. The name is still absent.',wd.withdraw);});
story('address','Change address A to B','Use application approval to change the address while keeping the same representative.',(add,get,st)=>{register(add,get);const bad=makeEvolution(get(),get().applications[0].id,200,false);st.forks.push({at:2,title:'Try an unapproved address change',steps:[{say:'Without accepted application evidence, the address cannot change.',action:bad,expect:step(get(),bad)}]});add('The application accepts the exact successor; the name now resolves to B (200).',makeEvolution(get(),get().applications[0].id,200));});
story('retire','Retire the name','Queue Update, observe pending resolution, then complete retirement.',(add,get)=>{register(add,get);add('Application-approved Update moves the NFT into request custody. Resolution is pending.',makeRelease(get(),get().applications[0].id,'update'));add('Fold Update; burn the NFT. The name is retired and occupied.',makeFold(get(),[get().requests[0].id]));});
story('delete','Delete the name','Queue Delete and make the name absent again.',(add,get,st)=>{register(add,get);add('Application-approved Delete moves the NFT to request custody.',makeRelease(get(),get().applications[0].id,'delete'));const a={escape:{request:get().requests[0].id}};st.forks.push({at:3,title:'Try escaping request custody',steps:[{say:'Terminal custody can leave only through completion.',action:a,expect:step(get(),a)}]});add('Fold Delete; the NFT burns, the name is absent, and its incarnation increases.',makeFold(get(),[get().requests[0].id]));});
story('batch','Delete and reinsert in a batch','Observe successive Delete then Insert effects with net zero representative mint.',(add,get,st)=>{register(add,get);add('Queue Delete.',makeRelease(get(),get().applications[0].id,'delete'));add('Queue Insert approved for the next incarnation.',makeInsert(get(),{datum:200,scope:[1]}));const ids=get().requests.map(r=>r.id).reverse();const batch=makeFold(get(),ids);batch.fold.mint=[];add('Atomic batch: Delete removes the old entry, then Insert installs address B. Logical burn and mint cancel.',batch);const replay=makeFold(get(),ids);st.forks.push({at:5,title:'Try replaying the spent requests',steps:[{say:'A completed request is unavailable and cannot be replayed.',action:replay,expect:step(get(),replay)}]});});
story('forged','An outsider cannot forge origin','Show an outsider’s request being refused at the authenticated-origin boundary.',(add,get)=>{const request=makeInsert(get()).createInsert.request;add('An outsider can post a request; the model marks its origin unauthenticated.',{outsider:{request}});add('Folding the outsider request is refused: no representative is minted.',makeFold(get(),[1]));});
writeFileSync(new URL('./stories.json',import.meta.url),JSON.stringify(stories,null,2)+'\n');
console.log(`wrote ${stories.length} immutable story trees`);
