{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Singular.CLI.Permanent
Description : Generated immutable identities of the permanent M1 contract
License     : Apache-2.0

Generated by tools/m1_identity.py from the built blueprint. A title supplied
by a caller is not recognition; compare the hash computed from the code.
-}
module Singular.CLI.Permanent (knownScripts) where

import Data.Text (Text)

-- | The only unapplied scripts recognized by this release.
knownScripts :: [(Text, Text)]
knownScripts =
    [
        ( "permanent_state.state"
        , "807d91e4dc360ab722ad2b3b47d6b3d000237992048f3333ae799aaa"
        )
    ,
        ( "request.request"
        , "5daa275eaf32556a5527035996e37f11072c51b1b4acd64ca2bdd320"
        )
    ,
        ( "permanent_witness.witness"
        , "4c87b7aa4c2f509c8de536243f98da7a44b48cfc5bb541e19c38f5a1"
        )
    ,
        ( "permanent_open_datum.open_datum"
        , "eeb82738115c80dc63d606513387b85bb93e35657744a34e318d3f03"
        )
    ]
