{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Singular.CLI.Permanent
Description : Generated immutable identities of the permanent M1 contract
License     : Apache-2.0

Generated by tools/m1_identity.py from the built blueprint. A title supplied
by a caller is not recognition; compare the hash computed from the code.
-}
module Singular.CLI.Permanent (knownScripts) where

import Data.Text (Text)

-- | The only unapplied scripts recognized by this release.
knownScripts :: [(Text, Text)]
knownScripts =
    [
        ( "state.state"
        , "68df9c42ebd4468be130e9cd5538a7af39cc31c146cda45f274cccc5"
        )
    ,
        ( "request.request"
        , "5daa275eaf32556a5527035996e37f11072c51b1b4acd64ca2bdd320"
        )
    ,
        ( "witness.witness"
        , "fde1eb8c2a91a1c2f571f4c2f7b3a2b6ef68339c39bbce5ce2037575"
        )
    ,
        ( "open_datum.open_datum"
        , "cdc67586fd5391249e862338e88120ec5921d3fc9f4cd84b8cce7c33"
        )
    ]
