#!/usr/bin/env python3
"""Generate and check the immutable script pins for the new permanent contract."""

import argparse
import hashlib
import json
from pathlib import Path


TITLES = [
    "state.state.spend",
    "request.request.spend",
    "witness.witness.mint",
    "open_datum.open_datum.mint",
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blueprint", type=Path, required=True)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parent.parent
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    blueprint = json.loads(args.blueprint.read_text())
    pins = []
    for title in TITLES:
        found = [v for v in blueprint["validators"] if v["title"] == title]
        if len(found) != 1:
            raise ValueError(f"expected exactly one {title}")
        validator = found[0]
        pins.append(
            {
                "title": title.rsplit(".", 1)[0],
                "hash": validator["hash"],
                "compiledCodeSha256": hashlib.sha256(
                    bytes.fromhex(validator["compiledCode"])
                ).hexdigest(),
                "parameters": len(validator.get("parameters", [])),
            }
        )
    manifest = {
        "contract": "permanent-m1",
        "model": "Singular.M1",
        "compiler": blueprint["preamble"]["compiler"],
        "scripts": pins,
        "registryEdges": ["insertActive", "updateTerminal"],
    }
    source = """{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Singular.CLI.Permanent
Description : Generated immutable identities of the permanent M1 contract
License     : Apache-2.0

Generated by tools/m1_identity.py from the built blueprint. A title supplied
by a caller is not recognition; compare the hash computed from the code.
-}
module Singular.CLI.Permanent (knownScripts) where

import Data.Text (Text)

-- | The only unapplied scripts recognized by this release.
knownScripts :: [(Text, Text)]
knownScripts =
"""
    source += (
        "\n".join(
            f'    {"[" if i == 0 else ","}\n        ( "{pin["title"]}"\n        , "{pin["hash"]}"\n        )'
            for i, pin in enumerate(pins)
        )
        + "\n    ]\n"
    )
    outputs = [
        (
            args.root / "onchain/permanent-contract.json",
            json.dumps(manifest, indent=2) + "\n",
        ),
        (args.root / "offchain/cli/src/Singular/CLI/Permanent.hs", source),
    ]
    for path, text in outputs:
        if args.check:
            if path.read_text() != text:
                raise SystemExit(f"stale permanent identity: {path}")
        else:
            path.write_text(text)
    print("Permanent contract: 4 compiled script identities and parameter counts bound")


if __name__ == "__main__":
    main()
